CREATE TABLE SAMPLE
(
    ID1                 VARCHAR,
    ID2                 VARCHAR,
    FRAMEWORK_TIMESTAMP TIMESTAMP DEFAULT NOW(),
    VVVVV               VARCHAR,

    CONSTRAINT PK_SAMPLE PRIMARY KEY (ID1, ID2)
);
